### ISSUE TITLE
Example usage with grunt

### ISSUE THREAD

**Issue by alwinmark** [timkelty/shipit-assets#3]
Hi,
I'm wondering how this is working with grunt and especially how I've to configure it.

so in my gruntfile.js I did:

```
   grunt.initConfig({
       shipit: {
            options: {assets: {}}
       },
       assets: {
          options: {assets: {}}, default: {assets: {}}
       }
   });

   var shiptassets = require("grunt-shipit")(grunt);
   var shiptassets = require("shipit-assets")(grunt);

```

But when I call `grunt assets:push` I always get:

```
Warning: Cannot read property 'assets' of undefined Use --force to continue
```

As far as I can see, shipt_utils is trying to get the configs from grunt.shipit.config but shipit is not the correct shipit object.

Is the grunt support broken or am I doing sth horribly wrong?

**Comment by timkelty** [comment]
I haven't tested this with Grunt recently, so it could be broken.

I'll take a look.

**Comment by timkelty** [comment]
Working fine via Grunt for me, I think your config is off.
Do you have other Shipit tasks working?

**Comment by timkelty** [comment]
Here's more of what I would expect:

```
  grunt.initConfig({
    shipit: {
      options: {
        workspace: '/tmp/github-monitor',
        deployTo: '/tmp/deploy_to',
        repositoryUrl: 'https://github.com/user/repo.git',
        ignores: ['.git', 'node_modules'],
        keepReleases: 2,
        key: '/path/to/key',
        shallowClone: true,
        assets: {
          'paths': [
            'public/uploads',
            'backup'
          ]
        },
      },
      staging: {
        servers: 'user@myserver.com'
      }
    }
  });

  grunt.loadNpmTasks('grunt-shipit');
  grunt.loadNpmTasks('shipit-deploy');
  grunt.loadNpmTasks('shipit-assets');
```

**Comment by alwinmark** [comment]
When I do this without grunt:
**shipitfile.js**

``` js
module.exports = function(shipit) {
    require('shipit-assets')(shipit);

    shipit.initConfig({
        default: {
            assets: {
                paths: ['assets'],
                localPaths: ['./dist/assets'],
                deployTo: '/var/www',
                options: []
            }
        },
        staging: {
            deployTo: '/var/www',
            servers: 'user@staging.de'
        }
    });
}

```

it is working by calling `node_modules/shipit-cli/bin/shipit dev1 assets:push`

When I try to convert it into the grunt schema, I get this one:

**Gruntfile.js**

``` js
    grunt.initConfig({
      shipit: {
       options: {
            deployTo: '/var/www',
            assets: {
                paths: ['assets'],
                localPaths: ['./dist/assets'],
                options: []
            }
        },
        staging: {
            deployTo: '/var/www',
            servers: 'user@staging1.de'
        }
      }
    };

    grunt.loadNpmTasks('grunt-deploy');
    grunt.loadNpmTasks('shipit-deploy');
    grunt.loadNpmTasks('shipit-assets');
```

When I now try to start the task by `grunt assets:push` (I don't know how to pass the environment)
Then I get following:

```
>> Local Npm module "shipit-deploy" not found. Is it installed?

Running "assets:push" task
Warning: Cannot read property 'assets' of undefined Use --force to continue.
TypeError: Cannot read property 'assets' of undefined
    at Shipit.transfer (/home/user/git/shop-prototype/node_modules/shipit-assets/lib/transfer.js:10:50)
    at /home/user/git/shop-prototype/node_modules/shipit-assets/tasks/assets/push.js:9:19
    at Object.<anonymous> (/home/user/git/shop-prototype/node_modules/shipit-assets/node_modules/shipit-utils/lib/register-task.js:16:21)
    at Object.thisTask.fn (/home/user/git/shop-prototype/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/home/user/git/shop-prototype/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/home/user/git/shop-prototype/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/home/user/git/shop-prototype/node_modules/grunt/lib/util/task.js:300:12)
    at Task.start (/home/user/git/shop-prototype/node_modules/grunt/lib/util/task.js:309:5)
    at Object.grunt.tasks (/home/user/git/shop-prototype/node_modules/grunt/lib/grunt.js:164:8)
    at Object.module.exports [as cli] (/home/user/git/shop-prototype/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

Aborted due to warnings.
```

**Grunt version**:

```
$ grunt -version
grunt-cli v0.1.13
grunt v0.4.5
```

**Shipit versions**:

```
 cat package.json | grep shipit
    "shipit": "^0.2.4",
    "shipit-assets": "^1.3.5",
    "shipit-cli": "^1.3.0"
```

**Comment by timkelty** [comment]
Ah ok - When using `grunt-shipit`, the command should look like:

`grunt shipit:dev1 assets:push`

**Comment by timkelty** [comment]
You can remove the `grunt.loadNpmTasks('shipit-deploy');` line if you're not using `shipit-deploy`.

**Comment by timkelty** [comment]
This goes for any tasks using `grunt-shipit`.
You're right though, there's no examples of this the the docs: https://github.com/shipitjs/grunt-shipit

**Comment by alwinmark** [comment]
Thanks that did the trick for me!

**Comment by timkelty** [comment]
Great!
